"use client";
import React,{useMemo,useState}from"react";
import"./dashboard.css";
import ChartPanel from"./dashboard/chart-panel";
import{exportExcel,exportPowerPoint}from"./dashboard/exporters";
import{displayDate,money,Result,UploadGroup}from"./dashboard/types";

export default function Home(){
 const[college,setCollege]=useState("");const[groups,setGroups]=useState<UploadGroup[]>([{name:"Plan 1",files:[]},{name:"Plan 2",files:[]},{name:"Plan 3",files:[]}]);const[password,setPassword]=useState("");const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(false);const[pptLoading,setPptLoading]=useState(false);const[error,setError]=useState("");const[search,setSearch]=useState("");const[policyFilter,setPolicyFilter]=useState("");
 const filtered=useMemo(()=>{if(!result)return[];const query=search.trim().toLowerCase();return result.cleaned_rows.filter(row=>(!policyFilter||row["Policy (New/Renewal)"]===policyFilter)&&(!query||Object.values(row).some(value=>String(value??"").toLowerCase().includes(query))))},[result,search,policyFilter]);
 const updateGroup=(index:number,patch:Partial<UploadGroup>)=>setGroups(current=>current.map((group,i)=>i===index?{...group,...patch}:group));
 async function analyze(){const flattened=groups.flatMap(group=>group.files.map(file=>({file,label:group.name.trim()||"Unnamed Plan"})));if(!flattened.length){setError("Upload at least one Excel file under a plan.");return}setLoading(true);setError("");setResult(null);try{const form=new FormData();flattened.forEach(({file})=>form.append("files",file));form.append("file_labels",JSON.stringify(flattened.map(({label})=>label)));form.append("college_name",college);form.append("password",password);const response=await fetch("/api/process",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Unable to process workbook.");setResult(data)}catch(exception:any){setError(exception.message||"Processing failed.")}finally{setLoading(false)}}
 function exportCsv(){if(!result?.cleaned_rows.length)return;const cols=result.meta.export_columns;const esc=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const csv=[cols.map(esc).join(","),...result.cleaned_rows.map(row=>cols.map(column=>esc(column==="Transaction_Date"?displayDate(row[column]):row[column])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="Cleaned_Insurance_Data.csv";a.click();URL.revokeObjectURL(a.href)}
 async function makePpt(){if(!result)return;setPptLoading(true);setError("");try{await exportPowerPoint(result)}catch(exception:any){setError(exception.message||"PowerPoint export failed.")}finally{setPptLoading(false)}}
 return <main><header className="hero"><div><span className="eyebrow">MULTI-YEAR • MULTI-PLAN EXCEL ANALYTICS</span><h1>Insurance Business Insights Dashboard</h1><p>Upload current and previous-year files for up to three plans from the same college, compare yearly and monthly performance, evaluate sum-insured enrolment and batch reach, and export management-ready Excel and PowerPoint reports.</p></div><div className="privacy">🔒 Files are processed only for this request</div></header>
 <section className="setupCard"><div className="collegeInput"><label>College / Institute name</label><input value={college} onChange={e=>setCollege(e.target.value)} placeholder="Enter college name"/></div><div className="password"><label>Common Excel password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter the common password"/></div><div className="planUploads">{groups.map((group,index)=><article className="planUpload" key={index}><input className="planName" value={group.name} onChange={e=>updateGroup(index,{name:e.target.value})} placeholder={`Plan ${index+1} name`}/><input id={`files-${index}`} type="file" multiple accept=".xlsx,.xlsm,.xls" onChange={e=>updateGroup(index,{files:Array.from(e.target.files||[])})}/><label htmlFor={`files-${index}`}><b>Upload plan files</b><span>{group.files.length?`${group.files.length} file(s): ${group.files.map(file=>file.name).join(", ")}`:"Add current year and previous-year files for this same plan"}</span></label></article>)}</div><button className="primary generate" onClick={analyze} disabled={loading}>{loading?"Analysing…":"Generate College Comparison"}</button>{error&&<div className="error">{error}</div>}</section>
 {result&&<><div className="toolbar"><div><b>{result.kpis.total_records} clean records • {result.kpis.years_compared} years • {result.kpis.plans_compared} plans</b><span>Processed {new Date(result.meta.processed_at).toLocaleString("en-IN")}</span></div><div className="toolbarActions"><button onClick={exportCsv}>Export CSV</button><button onClick={makePpt} disabled={pptLoading}>{pptLoading?"Creating PPT…":"Export Presentable PPT"}</button><button className="primary small" onClick={()=>exportExcel(result)}>Export Complete Excel</button></div></div>
 <section className="kpis">{[["Clean records",result.kpis.total_records],["Transaction value",money(result.kpis.total_transaction_amount)],["Total premium",money(result.kpis.total_premium)],["Years compared",result.kpis.years_compared],["Plans compared",result.kpis.plans_compared],["Recommended plan",result.kpis.top_plan],["Most selected sum insured",result.kpis.most_selected_sum_insured]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{String(value)}</strong></article>)}</section>
 <section className="insights"><div><span className="eyebrow">AUTOMATIC BUSINESS FINDINGS</span><h2>What the college data is saying</h2></div><ol>{result.insights.map((insight,index)=><li key={index}>{insight}</li>)}</ol></section>
 {!!result.analysis.plan_recommendation?.length&&<section className="recommendations"><div><span className="eyebrow">PLAN SUITABILITY</span><h2>Which plan appears most suitable</h2><p>The score combines transaction volume, transaction value, batch reach and sum-insured enrolment. Use it with service quality and policy terms before final selection.</p></div><div className="recommendationGrid">{result.analysis.plan_recommendation.map((row,index)=><article key={row.label} className={index===0?"best":""}><span>Rank {index+1}</span><strong>{row.label}</strong><b>{row.suitability_score}/100</b><small>{row.count} records • {row.batch_count} batches • {money(row.amount)}</small></article>)}</div></section>}
 <section className="sectionTitle"><span className="eyebrow">YEAR AND PLAN COMPARISON</span><h2>Compare the same plans across previous and current years</h2></section><section className="gridCharts"><ChartPanel title="Year-wise business trend" subtitle="Annual transaction value, premium or enrolment count" data={result.analysis.yearly_trend||[]} initialType="bar" initialMetric="amount" chronological/><ChartPanel title="Month-by-year comparison" subtitle="Compare January–December performance between years" data={result.analysis.month_by_year||[]} initialType="line" initialMetric="amount" multiSeries/><ChartPanel title="Overall plan comparison" subtitle="Compare sales, members, batches or sum-insured enrolments" data={result.analysis.plan_comparison||[]} initialType="bar" initialMetric="amount"/><ChartPanel title="Plan performance by year" subtitle="See which plan performed best in each transaction year" data={result.analysis.plan_year_comparison||[]} initialType="bar" initialMetric="amount" multiSeries/><ChartPanel title="Monthly sales movement by plan" subtitle="Track each plan across all uploaded months and years" data={result.analysis.plan_month_comparison||[]} initialType="line" initialMetric="amount" multiSeries chronological/><ChartPanel title="Sum-insured enrolments by plan" subtitle="Which plan enrolled the most members at each cover level" data={result.analysis.plan_sum_insured||[]} initialType="bar" initialMetric="count" multiSeries/><ChartPanel title="Batch-wise plan comparison" subtitle="Compare every nonblank batch across all uploaded plans" data={result.analysis.plan_batch_comparison||[]} initialType="bar" initialMetric="count" multiSeries/><ChartPanel title="Plan suitability score" subtitle="Composite comparison for college-level decision support" data={result.analysis.plan_recommendation||[]} initialType="bar" initialMetric="suitability_score"/></section>
 <section className="sectionTitle"><span className="eyebrow">PORTFOLIO ANALYSIS</span><h2>Additional customer, geography, course and insurance trends</h2></section><section className="gridCharts">{[["Monthly transaction trend","Transaction month versus transaction amount","monthly_trend","line","amount",false,true],["Transaction date trend","Transaction date versus transaction amount","daily_trend","line","amount",false,true],["Passing year / batch analysis","All nonblank batches in the uploaded files","passing_year","bar","count",false,false],["State analysis","Geographical transaction performance by state","state","bar","count",false,false],["City analysis","Geographical transaction performance by city","city","bar","count",false,false],["Pincode analysis","Local transaction concentration by pincode","pincode","bar","count",false,false],["Course analysis","Course-wise participation and transaction value","course","bar","count",false,false],["Nominee relationship","Nominee composition from available data","nominee_relationship","pie","count",false,false],["Most selected sum insured","Insurance cover chosen most frequently","sum_insured","bar","count",false,false],["Premium-band effectiveness","Premium ranges by purchase count and value","premium_bands","bar","count",false,false],["Insurance products","Products or policy types taken most often","insurance_products","bar","count",false,false],["Insurer analysis","Business contribution by insurer","insurers","bar","count",false,false]].map(([title,subtitle,key,type,metric,multi,chrono])=><ChartPanel key={String(key)} title={String(title)} subtitle={String(subtitle)} data={result.analysis[String(key)]||[]} initialType={type as any} initialMetric={metric as any} multiSeries={Boolean(multi)} chronological={Boolean(chrono)}/>)}{result.meta.policy_included&&<ChartPanel title="New versus Renewal" subtitle="Only valid New and Renewal values are included" data={result.analysis.policy||[]} initialType="pie" initialMetric="count"/>}</section>
 <section className="dataPanel"><div className="dataHead"><div><h2>Cleaned export data</h2><p>Displayed dates use DD/Month Name/YYYY. Excel export keeps original cleaned row order and does not sort by date, payment or name.</p></div><div className="filters"><input placeholder="Search all fields" value={search} onChange={e=>setSearch(e.target.value)}/>{result.meta.policy_included&&<select value={policyFilter} onChange={e=>setPolicyFilter(e.target.value)}><option value="">All policies</option><option>New</option><option>Renewal</option></select>}</div></div><div className="tableWrap"><table><thead><tr>{result.meta.export_columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{filtered.slice(0,500).map((row,index)=><tr key={index}>{result.meta.export_columns.map(column=><td key={column}>{column==="transaction_amount"?money(row[column]):column==="Transaction_Date"?displayDate(row[column]):String(row[column]??"")}</td>)}</tr>)}</tbody></table></div><div className="tableFoot">Showing {Math.min(filtered.length,500)} of {filtered.length} filtered records. Excel export always contains all cleaned rows in source order.</div></section>
 <section className="quality"><h2>Data cleaning summary</h2><div>{[["Rows received",result.data_quality.rows_before_cleaning],["Invalid dates removed",result.data_quality.invalid_dates_removed],["Exact duplicates removed",result.data_quality.exact_duplicates_removed],["Duplicate transaction IDs removed",result.data_quality.duplicate_transaction_ids_removed],["Final export rows",result.data_quality.final_rows]].map(([label,value])=><p key={String(label)}><span>{label}</span><b>{String(value)}</b></p>)}</div></section></>}
 </main>;
}
