import{excelDate,Item,Metric,metricLabel,money,Result}from"./types";

function addSheet(XLSX:any,workbook:any,name:string,rows:any[],dateColumn=false){
 const values=rows.length?rows.map(row=>({...row,...(dateColumn&&row.Transaction_Date?{Transaction_Date:excelDate(row.Transaction_Date)}:{})})):[{Status:"No data available"}];
 const worksheet=XLSX.utils.json_to_sheet(values,{cellDates:true});worksheet["!cols"]=Object.keys(values[0]).map(key=>({wch:Math.min(42,Math.max(13,key.length+3))}));
 if(dateColumn&&values.length){const headers=Object.keys(values[0]);const index=headers.indexOf("Transaction_Date");if(index>=0){for(let row=2;row<=values.length+1;row+=1){const address=XLSX.utils.encode_cell({r:row-1,c:index});if(worksheet[address])worksheet[address].z="dd/mmmm/yyyy"}}}
 XLSX.utils.book_append_sheet(workbook,worksheet,name.slice(0,31));
}

export async function exportExcel(result:Result){
 const XLSX=await import("xlsx");const workbook=XLSX.utils.book_new();
 addSheet(XLSX,workbook,"Dashboard_Summary",Object.entries(result.kpis).map(([Metric,Value])=>({Metric,Value})));
 addSheet(XLSX,workbook,"Export_Data",result.cleaned_rows,true);addSheet(XLSX,workbook,"Analysis_Data",result.analysis_rows,true);
 const sheets:[string,string][]=[["Yearly_Trend","yearly_trend"],["Month_By_Year","month_by_year"],["Plan_Comparison","plan_comparison"],["Plan_Recommendation","plan_recommendation"],["Plan_Year","plan_year_comparison"],["Plan_Month","plan_month_comparison"],["Plan_Sum_Insured","plan_sum_insured"],["Plan_Batch","plan_batch_comparison"],["Monthly_Trend","monthly_trend"],["Daily_Trend","daily_trend"],["State_Analysis","state"],["City_Analysis","city"],["Pincode_Analysis","pincode"],["Passing_Year_Batch","passing_year"],["Course_Analysis","course"],["Sum_Insured","sum_insured"],["Premium_Bands","premium_bands"],["Nominee_Relationship","nominee_relationship"],["Insurance_Products","insurance_products"],["Insurers","insurers"]];
 sheets.forEach(([name,key])=>addSheet(XLSX,workbook,name,result.analysis[key]||[]));
 addSheet(XLSX,workbook,"Business_Insights",result.insights.map((Insight,index)=>({No:index+1,Insight})));addSheet(XLSX,workbook,"Data_Quality",Object.entries(result.data_quality).filter(([key])=>key!=="processing_log").map(([Metric,Value])=>({Metric,Value})));
 XLSX.writeFile(workbook,`Insurance_College_Plan_Comparison_${new Date().toISOString().slice(0,10)}.xlsx`,{cellDates:true});
}

function native(data:Item[],metric:Metric,seriesKey=false){
 if(!seriesKey)return[{name:metricLabel[metric],labels:data.map(row=>row.label),values:data.map(row=>Number(row[metric]||0))}];
 const series=Array.from(new Set(data.map(row=>String(row.series||"Data"))));const labels=Array.from(new Set(data.map(row=>row.label)));
 return series.map(name=>({name,labels,values:labels.map(label=>Number(data.find(row=>row.label===label&&row.series===name)?.[metric]||0))}));
}

export async function exportPowerPoint(result:Result){
 const module:any=await import("pptxgenjs");const PptxGenJS=module.default||module;const pptx:any=new PptxGenJS();pptx.layout="LAYOUT_WIDE";pptx.author="Insurance Business Insights Dashboard";pptx.title=`${result.meta.college_name||"College"} Insurance Plan Comparison`;
 const C={navy:"102033",teal:"0A6A61",blue:"2576A8",orange:"E58B37",purple:"7E57C2",gray:"667B8E",pale:"F2F6FA",white:"FFFFFF",line:"D7E1E8"};
 const header=(slide:any,title:string,subtitle:string)=>{slide.background={color:C.white};slide.addText(title,{x:.55,y:.35,w:9.5,h:.4,fontSize:24,bold:true,color:C.navy,margin:0});slide.addText(subtitle,{x:.55,y:.83,w:11.8,h:.28,fontSize:10,color:C.gray,margin:0});slide.addShape(pptx.ShapeType.line,{x:.55,y:1.16,w:12.1,h:0,line:{color:C.line}})};
 let slide=pptx.addSlide();slide.background={color:C.navy};slide.addText("Insurance Plan Performance Comparison",{x:.75,y:1.35,w:11.5,h:.8,fontSize:34,bold:true,color:C.white,margin:0});slide.addText(result.meta.college_name||"College-level multi-plan and multi-year analysis",{x:.78,y:2.3,w:10.8,h:.5,fontSize:18,color:"B8D9D5",margin:0});slide.addText(`Compared ${result.kpis.plans_compared} plans across ${result.kpis.years_compared} transaction years`,{x:.78,y:3,w:9,h:.35,fontSize:14,color:C.white,margin:0});
 slide=pptx.addSlide();header(slide,"Executive summary","Portfolio scale, year coverage and recommended plan");const cards=[["Clean records",result.kpis.total_records],["Transaction value",money(result.kpis.total_transaction_amount)],["Years compared",result.kpis.years_compared],["Plans compared",result.kpis.plans_compared],["Recommended plan",result.kpis.top_plan],["Most selected sum insured",result.kpis.most_selected_sum_insured]];cards.forEach(([label,value],index)=>{const x=.6+(index%3)*4.15;const y=1.5+Math.floor(index/3)*1.45;slide.addText(String(label).toUpperCase(),{x,y,w:3.8,h:.25,fontSize:8,bold:true,color:C.gray,margin:0});slide.addText(String(value),{x,y:y+.28,w:3.8,h:.72,fontSize:18,bold:true,color:C.navy,fill:{color:C.pale},line:{color:C.line},margin:.12,valign:"mid"})});
 slide=pptx.addSlide();header(slide,"Year and month trends","Compare the same plan periods across previous and current years");if(result.analysis.yearly_trend?.length)slide.addChart(pptx.ChartType.column,native(result.analysis.yearly_trend,"amount"),{x:.55,y:1.45,w:5.9,h:4.9,showLegend:false,showTitle:true,title:"Transaction amount by year",chartColors:[C.teal]});if(result.analysis.month_by_year?.length)slide.addChart(pptx.ChartType.line,native(result.analysis.month_by_year,"amount",true),{x:6.75,y:1.45,w:5.9,h:4.9,showLegend:true,showTitle:true,title:"Month-by-month comparison across years",chartColors:[C.teal,C.blue,C.orange,C.purple]});
 slide=pptx.addSlide();header(slide,"Plan suitability comparison","Sales, enrolments, batch reach and sum-insured participation");if(result.analysis.plan_comparison?.length)slide.addChart(pptx.ChartType.bar,native(result.analysis.plan_comparison,"amount"),{x:.55,y:1.45,w:6,h:4.9,showTitle:true,title:"Transaction amount by plan",showLegend:false,chartColors:[C.blue]});const rec=(result.analysis.plan_recommendation||[]).slice(0,3).map((row,index)=>({text:`${index+1}. ${row.label} — suitability ${row.suitability_score}/100; ${row.count} records; ${row.batch_count} batches; ${money(row.amount)}`,options:{breakLine:true}}));slide.addText(rec.length?rec:"No plan comparison data available.",{x:6.9,y:1.65,w:5.6,h:3.8,fontSize:16,color:C.navy,breakLine:true,margin:.15,valign:"top"});
 slide=pptx.addSlide();header(slide,"Plan by year and month","Identify which plan performed best in each year and month");if(result.analysis.plan_year_comparison?.length)slide.addChart(pptx.ChartType.column,native(result.analysis.plan_year_comparison,"amount",true),{x:.55,y:1.45,w:5.9,h:4.9,showTitle:true,title:"Plan sales by year",showLegend:true,chartColors:[C.teal,C.blue,C.orange]});if(result.analysis.plan_month_comparison?.length)slide.addChart(pptx.ChartType.line,native(result.analysis.plan_month_comparison.slice(-36),"amount",true),{x:6.75,y:1.45,w:5.9,h:4.9,showTitle:true,title:"Monthly sales by plan",showLegend:true,chartColors:[C.teal,C.blue,C.orange]});
 slide=pptx.addSlide();header(slide,"Coverage and batch comparison","Which plan enrols the most people at each cover and across batches");if(result.analysis.plan_sum_insured?.length)slide.addChart(pptx.ChartType.column,native(result.analysis.plan_sum_insured,"count",true),{x:.55,y:1.45,w:5.9,h:4.9,showTitle:true,title:"Sum-insured enrolments by plan",showLegend:true,chartColors:[C.teal,C.blue,C.orange]});if(result.analysis.plan_batch_comparison?.length)slide.addChart(pptx.ChartType.bar,native(result.analysis.plan_batch_comparison,"count",true),{x:6.75,y:1.45,w:5.9,h:4.9,showTitle:true,title:"Batch-wise plan participation",showLegend:true,chartColors:[C.teal,C.blue,C.orange]});
 slide=pptx.addSlide();header(slide,"Business findings","Key conclusions generated from the uploaded college data");slide.addText(result.insights.map((insight,index)=>({text:`${index+1}. ${insight}`,options:{breakLine:true}})),{x:.75,y:1.5,w:11.7,h:4.9,fontSize:17,color:C.navy,breakLine:true,margin:.15,valign:"top"});await pptx.writeFile({fileName:`Insurance_Plan_Comparison_${new Date().toISOString().slice(0,10)}.pptx`});
}
